Add option to show or hide close icon from notifications
lookout/gringotts pull request #100
Opened 2020-11-17 08:38 UTC by kpunith8

2020-11-17 08:43 UTC, MohammedRajaAtLookout commented
I was not able to create a PR from my machine. It shows a permission issue, maybe I messed with the ssh keys.
It is just a small change and requested Punith to create a PR.
Thank Punith!

2020-11-17 16:42 UTC, eugenet8k requested changes

2020-11-17 16:42 UTC, eugenet8k commented on views/notification.hbs
> +{{#if showCloseButton}}
To make this work, you need to update all existing code and pass `showCloseButton: true`. And only for the case where you need to hide the button you would be able to skip this parameter. The requirement is to do quite opposite, having a flag that allows removing the close button from notification if it's not needed, where by default it should stay visible.

2020-11-17 16:42 UTC, eugenet8k commented on views/notification-view.spec.coffee
> +    model = new Chaplin.Model {opts, showCloseButton}
the newly adding parameter should be part of `opts` object. "opts" name stand for options and this is yet another option.

2020-11-17 16:44 UTC, eugenet8k commented
Yeh, if you had a custom config in your «~/.npmrc» for Lookout artifactory that might affect regular GitHub access.

Unfortunately the code in your PR is wrong.

> 17 нояб. 2020 г., в 12:43 AM, MohammedRajaAtLookout <notifications@github.com> написал(а):
> 
> 
> I was not able to create a PR from my machine. It shows a permission issue, maybe I messed with the ssh keys.
> It is just a small change and requested Punith to create a PR.
> Thank Punith!
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub <https://github.com/lookout/gringotts/pull/100#issuecomment-728778476>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABEVBWG66SLWPVANWJWGUXDSQIZTRANCNFSM4TYIA6GA>.
>

2020-11-19 15:40 UTC, eugenet8k commented
Looks good thank you

2020-11-19 15:48 UTC, eugenet8k requested changes
There should be one commit in this PR.

2020-11-19 16:04 UTC, kpunith8 commented
> Please squash two commits into one before merging.

I squashed into a single commit

2020-11-19 18:16 UTC, merged